"""empty message

Revision ID: 029d5745cfd2
Revises: 
Create Date: 2025-04-17 18:49:24.992638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '029d5745cfd2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_authors'))
    )
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_authors_name'), ['name'], unique=False)

    op.create_table('awards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_awards'))
    )
    with op.batch_alter_table('awards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_awards_name'), ['name'], unique=False)

    op.create_table('books',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('series', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('isbn', sa.String(), nullable=False),
    sa.Column('book_format', sa.String(), nullable=True),
    sa.Column('edition', sa.String(), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('publish_date', sa.String(), nullable=True),
    sa.Column('first_publish_date', sa.String(), nullable=True),
    sa.Column('num_ratings', sa.Integer(), nullable=False),
    sa.Column('ratings_by_stars', sa.String(), nullable=False),
    sa.Column('liked_percent', sa.Float(), nullable=False),
    sa.Column('setting', sa.String(), nullable=False),
    sa.Column('cover_img', sa.String(), nullable=False),
    sa.Column('bbe_score', sa.Integer(), nullable=False),
    sa.Column('bbe_votes', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_books'))
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_books_title'), ['title'], unique=False)

    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_characters'))
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_characters_name'), ['name'], unique=False)

    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_genres'))
    )
    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_genres_name'), ['name'], unique=False)

    op.create_table('publishers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publishers'))
    )
    with op.batch_alter_table('publishers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publishers_name'), ['name'], unique=False)

    op.create_table('reading_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reading_statuses')),
    sa.UniqueConstraint('name', name=op.f('uq_reading_statuses_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('pp', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_date_created'), ['date_created'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('book_authors',
    sa.Column('book_id', sa.String(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], name=op.f('fk_book_authors_author_id_authors')),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_book_authors_book_id_books')),
    sa.PrimaryKeyConstraint('book_id', 'author_id', name=op.f('pk_book_authors'))
    )
    op.create_table('book_awards',
    sa.Column('book_id', sa.String(), autoincrement=False, nullable=False),
    sa.Column('award_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['award_id'], ['awards.id'], name=op.f('fk_book_awards_award_id_awards')),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_book_awards_book_id_books')),
    sa.PrimaryKeyConstraint('book_id', 'award_id', name=op.f('pk_book_awards'))
    )
    op.create_table('book_characters',
    sa.Column('book_id', sa.String(), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_book_characters_book_id_books')),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_book_characters_character_id_characters')),
    sa.PrimaryKeyConstraint('book_id', 'character_id', name=op.f('pk_book_characters'))
    )
    op.create_table('book_genres',
    sa.Column('book_id', sa.String(), autoincrement=False, nullable=False),
    sa.Column('genre_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_book_genres_book_id_books')),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_book_genres_genre_id_genres')),
    sa.PrimaryKeyConstraint('book_id', 'genre_id', name=op.f('pk_book_genres'))
    )
    op.create_table('book_publisher',
    sa.Column('book_id', sa.String(), autoincrement=False, nullable=False),
    sa.Column('publisher_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_book_publisher_book_id_books')),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], name=op.f('fk_book_publisher_publisher_id_publishers')),
    sa.PrimaryKeyConstraint('book_id', 'publisher_id', name=op.f('pk_book_publisher'))
    )
    op.create_table('book_statuses',
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('book_id', sa.String(), autoincrement=False, nullable=False),
    sa.Column('reading_status_id', sa.Integer(), nullable=False),
    sa.Column('finished_chapters', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_book_statuses_book_id_books')),
    sa.ForeignKeyConstraint(['reading_status_id'], ['reading_statuses.id'], name=op.f('fk_book_statuses_reading_status_id_reading_statuses')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_book_statuses_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'book_id', name=op.f('pk_book_statuses'))
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('book_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_comments_book_id_books')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_comments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_date_created'), ['date_created'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_user_id'), ['user_id'], unique=False)

    op.create_table('user_favorites',
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('book_id', sa.String(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_user_favorites_book_id_books')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_favorites_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'book_id', name=op.f('pk_user_favorites'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_favorites')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_user_id'))
        batch_op.drop_index(batch_op.f('ix_comments_date_created'))

    op.drop_table('comments')
    op.drop_table('book_statuses')
    op.drop_table('book_publisher')
    op.drop_table('book_genres')
    op.drop_table('book_characters')
    op.drop_table('book_awards')
    op.drop_table('book_authors')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_date_created'))

    op.drop_table('users')
    op.drop_table('reading_statuses')
    with op.batch_alter_table('publishers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publishers_name'))

    op.drop_table('publishers')
    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_genres_name'))

    op.drop_table('genres')
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_characters_name'))

    op.drop_table('characters')
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_books_title'))

    op.drop_table('books')
    with op.batch_alter_table('awards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_awards_name'))

    op.drop_table('awards')
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authors_name'))

    op.drop_table('authors')
    # ### end Alembic commands ###
