"""empty message

Revision ID: 731ca86deda8
Revises: 
Create Date: 2025-03-01 14:15:12.871140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '731ca86deda8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('date_created', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('profile_picture', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('_alembic_tmp_books')
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('book_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('uid',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('comment',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('date_created',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('date_created',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('comment',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('uid',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('book_id',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    op.create_table('_alembic_tmp_books',
    sa.Column('book_id', sa.TEXT(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('series', sa.TEXT(), nullable=True),
    sa.Column('author', sa.TEXT(), nullable=True),
    sa.Column('rating', sa.FLOAT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('language', sa.TEXT(), nullable=True),
    sa.Column('isbn', sa.TEXT(), nullable=False),
    sa.Column('genres', sa.TEXT(), nullable=True),
    sa.Column('characters', sa.TEXT(), nullable=True),
    sa.Column('book_format', sa.TEXT(), nullable=True),
    sa.Column('edition', sa.TEXT(), nullable=True),
    sa.Column('pages', sa.INTEGER(), nullable=True),
    sa.Column('publisher', sa.TEXT(), nullable=True),
    sa.Column('publish_date', sa.TEXT(), nullable=True),
    sa.Column('awards', sa.TEXT(), nullable=True),
    sa.Column('num_ratings', sa.FLOAT(), nullable=True),
    sa.Column('ratings_by_stars', sa.TEXT(), nullable=True),
    sa.Column('liked_percent', sa.FLOAT(), nullable=True),
    sa.Column('setting', sa.TEXT(), nullable=True),
    sa.Column('cover_img', sa.TEXT(), nullable=True),
    sa.Column('bbe_score', sa.FLOAT(), nullable=True),
    sa.Column('bbe_votes', sa.INTEGER(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.drop_table('users')
    # ### end Alembic commands ###
