"""empty message

Revision ID: df2b2b38e438
Revises: 
Create Date: 2025-02-22 05:12:29.189763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df2b2b38e438'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('book_id', sa.String(), nullable=False),
    sa.Column('isbn', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('series', sa.Text(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('genres', sa.Text(), nullable=True),
    sa.Column('characters', sa.Text(), nullable=True),
    sa.Column('book_format', sa.Text(), nullable=True),
    sa.Column('edition', sa.Text(), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('publisher', sa.Text(), nullable=True),
    sa.Column('publish_date', sa.Text(), nullable=True),
    sa.Column('awards', sa.Text(), nullable=True),
    sa.Column('num_ratings', sa.Float(), nullable=True),
    sa.Column('ratings_by_stars', sa.Text(), nullable=True),
    sa.Column('liked_percent', sa.Float(), nullable=True),
    sa.Column('setting', sa.Text(), nullable=True),
    sa.Column('cover_img', sa.Text(), nullable=True),
    sa.Column('bbe_score', sa.Float(), nullable=True),
    sa.Column('bbe_votes', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_table('users',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('date_created', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('books')
    # ### end Alembic commands ###
